"""Coverage supplement for release_models — the console-format branches.

``test_release_models.py`` covers the dataclasses, ``to_dict``, and the
happy-path ``format_console_output``. This file covers the remaining
branches: failing/critical/non-critical gates, blockers, warnings,
summary, and escalated/failed agent rows.

The module was previously in the coverage ``omit`` list (mislabeled
"Requires LLM API calls" — it is pure Enums + dataclasses + console
formatting, no LLM). Removed from ``omit`` alongside this file.

Copyright 2026 Smart-AI-Memory
Licensed under Apache 2.0
"""

from __future__ import annotations

import pytest

from attune.agents.release.release_models import (
    QualityGate,
    ReleaseAgentResult,
    ReleaseReadinessReport,
    Tier,
)


class TestFormatConsoleOutputBranches:
    """Exercise every conditional section of format_console_output()."""

    def _full_report(self) -> ReleaseReadinessReport:
        return ReleaseReadinessReport(
            approved=False,
            confidence="low",
            quality_gates=[
                QualityGate(name="coverage", threshold=80.0, actual=90.0, passed=True),
                QualityGate(
                    name="critical_issues",
                    threshold=0.0,
                    actual=2.0,
                    passed=False,
                    critical=True,
                ),
                QualityGate(
                    name="doc_coverage",
                    threshold=80.0,
                    actual=70.0,
                    passed=False,
                    critical=False,
                ),
            ],
            agent_results=[
                ReleaseAgentResult(
                    agent_id="a1",
                    agent_role="Security",
                    success=True,
                    tier_used=Tier.CHEAP,
                ),
                ReleaseAgentResult(
                    agent_id="a2",
                    agent_role="Coverage",
                    success=False,
                    tier_used=Tier.PREMIUM,
                    escalated=True,
                    execution_time_ms=1234.0,
                ),
            ],
            blockers=["2 critical issues found"],
            warnings=["doc coverage below threshold"],
            summary="Not ready: resolve critical issues first.",
            total_duration=12.5,
            total_cost=0.42,
        )

    def test_renders_all_sections(self):
        out = self._full_report().format_console_output()

        # Header + status (not approved).
        assert "NOT READY" in out
        assert "Confidence: LOW" in out
        # Gate icons: PASS, BLOCK (critical fail), WARN (non-critical fail).
        assert "[PASS]" in out
        assert "[BLOCK]" in out
        assert "[WARN]" in out
        # Blockers + warnings + summary sections.
        assert "BLOCKERS" in out
        assert "2 critical issues found" in out
        assert "WARNINGS" in out
        assert "doc coverage below threshold" in out
        assert "SUMMARY" in out
        assert "resolve critical issues first" in out
        # Agent rows: OK + FAIL with escalation marker.
        assert "[OK] Security" in out
        assert "[FAIL] Coverage" in out
        assert "(escalated)" in out

    def test_approved_report_minimal_sections(self):
        """Approved report with no blockers/warnings/summary skips those."""
        report = ReleaseReadinessReport(approved=True, confidence="high")
        out = report.format_console_output()

        assert "READY FOR RELEASE" in out
        assert "BLOCKERS" not in out
        assert "WARNINGS" not in out
        assert "SUMMARY" not in out


class TestQualityGatePostInit:
    """__post_init__ auto-generates a message only when none is given."""

    def test_message_autogenerated_when_absent(self):
        gate = QualityGate(name="coverage", threshold=80.0, actual=85.0, passed=True)
        assert "coverage" in gate.message
        assert "PASS" in gate.message

    def test_fail_message_says_fail(self):
        gate = QualityGate(name="quality", threshold=7.0, actual=5.0, passed=False)
        assert "FAIL" in gate.message

    def test_explicit_message_preserved(self):
        gate = QualityGate(name="x", threshold=1.0, message="custom note")
        assert gate.message == "custom note"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
