"""Deterministic library-health metrics snapshot for the ops dashboard.

Productizes ``docs/reports/library-health-*.md`` (see
``docs/specs/ops-dashboard-polish/decisions.md`` Phase E) into a
standing dashboard surface. Per the ratified decisions:

1. **Deterministic only.** Every signal here comes from a local tool
   or a read-only API call — coverage (Codecov), complexity (radon),
   churn (git log), the four docs gates, SLOC/TODO counts, and open
   PRs/issues (``gh`` CLI). The LLM judgment layer (narrative
   findings, ranked improvement plan) is never regenerated by this
   module — the dashboard route links to the latest
   ``docs/reports/library-health-*.md`` instead.
2. **Per-signal degradation.** Each signal is collected independently
   and wrapped by :func:`_safe`: a failure (network error, missing
   CLI, subprocess crash) degrades that ONE signal to
   ``{"status": "unavailable", "reason": ...}`` — the snapshot as a
   whole never raises. This matters most for the network-dependent
   signals (Codecov, ``gh``), which are the most likely to fail in a
   sandboxed or offline environment.
3. **No scheduler.** Nothing in this module runs on a timer. Callers
   (the CLI entry point, the dashboard's staleness check + Refresh
   button) decide when to collect.

Persistence mirrors ``attune.ops.sweep_results``: atomic
tempfile+``os.replace`` writes to
``<attune_home>/ops/health/<timestamp>.json`` and a ``latest.json``
sidecar the dashboard reads without needing to list the directory.

Copyright 2026 Smart-AI-Memory
Licensed under the Apache License, Version 2.0
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
import subprocess
import sys
import tempfile
import threading
from collections import Counter
from collections.abc import Callable
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from radon.complexity import cc_rank, cc_visit

logger = logging.getLogger(__name__)

SCHEMA_VERSION = 1
DEFAULT_REPO_SLUG = "Smart-AI-Memory/attune-ai"
DEFAULT_TIMEOUT_SECONDS = 30
DEFAULT_STALE_AFTER_HOURS = 12

RESULTS_SUBDIR = ("ops", "health")

_TODO_RE = re.compile(r"\b(?:TODO|FIXME|XXX)\b")

# name -> (script filename, extra argv). Each is invoked as
# ``python <script> --format json`` and must exit 0 (clean) or
# non-zero (findings present) with a JSON body on stdout either way —
# a non-zero exit is a REAL signal (findings exist), not a collection
# failure, so it is captured as ``clean: False``, not ``unavailable``.
_DOC_GATE_SCRIPTS: dict[str, str] = {
    "doc_import_audit": "audit_doc_imports.py",
    "docs_wiring_audit": "audit_docs_wiring.py",
    "help_completeness": "check_help_completeness.py",
}


# ---------------------------------------------------------------------------
# Per-signal isolation
# ---------------------------------------------------------------------------


def _safe(fn: Callable[..., Any], *args: Any, **kwargs: Any) -> dict[str, Any]:
    """Run one signal collector, never letting it crash the snapshot.

    Returns ``{"status": "ok", "value": <result>}`` on success or
    ``{"status": "unavailable", "reason": <str>}`` on any exception.
    The broad ``except Exception`` is INTENTIONAL — signals call out
    to networks, subprocesses, and third-party libraries whose
    failure modes are not fully enumerable, and per decision 1 a
    single flaky signal must never take down the whole snapshot.
    """
    try:
        value = fn(*args, **kwargs)
    except Exception as exc:  # noqa: BLE001
        reason = str(exc) or exc.__class__.__name__
        logger.warning("health_snapshot: signal %r failed: %s", getattr(fn, "__name__", fn), reason)
        return {"status": "unavailable", "reason": reason}
    return {"status": "ok", "value": value}


# ---------------------------------------------------------------------------
# Signal: coverage (Codecov API)
# ---------------------------------------------------------------------------


def _signal_coverage(repo_slug: str, *, timeout: int) -> dict[str, Any]:
    import requests

    owner, _, repo = repo_slug.partition("/")
    if not owner or not repo:
        raise ValueError(f"repo_slug must be 'owner/repo', got {repo_slug!r}")

    url = f"https://api.codecov.io/api/v2/github/{owner}/repos/{repo}/"
    headers = {"Accept": "application/json"}
    token = os.environ.get("CODECOV_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"

    resp = requests.get(url, headers=headers, timeout=timeout)
    resp.raise_for_status()
    payload = resp.json()

    coverage = payload.get("coverage")
    if coverage is None:
        coverage = (payload.get("totals") or {}).get("coverage")
    if coverage is None:
        raise RuntimeError("codecov response missing a coverage field")
    return {"coverage_percent": round(float(coverage), 2), "source": "codecov_api_v2"}


# ---------------------------------------------------------------------------
# Signal: complexity (radon)
# ---------------------------------------------------------------------------


def _file_complexity_scores(path: Path) -> list[float]:
    """Cyclomatic-complexity scores for every block in one file.

    Unreadable or unparsable files (encoding issues, syntax errors in
    a file radon can't handle) contribute no scores rather than
    aborting the whole complexity signal — matches how the repo's own
    complexity ratchet test tolerates a handful of unparsable files.
    """
    try:
        code = path.read_text(encoding="utf-8")
        blocks = cc_visit(code)
    except (OSError, UnicodeDecodeError, SyntaxError):
        return []
    return [block.complexity for block in blocks]


def _signal_complexity(project_root: Path) -> dict[str, Any]:
    src_dir = project_root / "src"
    scores: list[float] = []
    for path in sorted(src_dir.rglob("*.py")):
        scores.extend(_file_complexity_scores(path))
    if not scores:
        raise RuntimeError(f"no complexity blocks found under {src_dir}")
    avg = sum(scores) / len(scores)
    d_or_worse = sum(1 for score in scores if cc_rank(score) >= "D")
    return {
        "avg_complexity": round(avg, 2),
        "avg_rank": cc_rank(avg),
        "blocks": len(scores),
        "d_or_worse_count": d_or_worse,
    }


# ---------------------------------------------------------------------------
# Signal: churn (git log)
# ---------------------------------------------------------------------------


def _run_git(args: list[str], *, cwd: Path, timeout: int) -> str:
    proc = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=True,
    )
    return proc.stdout


def _signal_churn(
    project_root: Path, *, timeout: int, window_days: int = 90, top_n: int = 10
) -> dict[str, Any]:
    out = _run_git(
        [
            "log",
            f"--since={window_days}.days",
            "--name-only",
            "--pretty=format:",
            "--",
            "src/",
        ],
        cwd=project_root,
        timeout=timeout,
    )
    files = [line.strip() for line in out.splitlines() if line.strip()]
    counts = Counter(files)
    top = counts.most_common(top_n)
    return {
        "window_days": window_days,
        "total_changes": len(files),
        "top_files": [{"path": path, "changes": n} for path, n in top],
    }


# ---------------------------------------------------------------------------
# Signal: docs gates
# ---------------------------------------------------------------------------


def _run_gate_script(script_name: str, project_root: Path, *, timeout: int) -> dict[str, Any]:
    script = project_root / "scripts" / script_name
    if not script.is_file():
        raise FileNotFoundError(f"scripts/{script_name} not found under {project_root}")
    proc = subprocess.run(
        [sys.executable, str(script), "--format", "json"],
        cwd=project_root,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    try:
        detail = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"scripts/{script_name} did not produce valid JSON on stdout") from exc
    return {"exit_code": proc.returncode, "clean": proc.returncode == 0, "detail": detail}


def _signal_doc_import_audit(project_root: Path, *, timeout: int) -> dict[str, Any]:
    return _run_gate_script(_DOC_GATE_SCRIPTS["doc_import_audit"], project_root, timeout=timeout)


def _signal_docs_wiring_audit(project_root: Path, *, timeout: int) -> dict[str, Any]:
    return _run_gate_script(_DOC_GATE_SCRIPTS["docs_wiring_audit"], project_root, timeout=timeout)


def _signal_help_completeness(project_root: Path, *, timeout: int) -> dict[str, Any]:
    return _run_gate_script(_DOC_GATE_SCRIPTS["help_completeness"], project_root, timeout=timeout)


def _signal_projection_drift(project_root: Path) -> dict[str, Any]:
    # Imported lazily: this pulls in attune.authoring, which is a
    # heavier import than the rest of this module needs on the
    # common path (a per-request page load that's usually reading a
    # cached snapshot, not collecting a fresh one).
    from attune.authoring.projector import check_projection_drift

    help_dir = project_root / ".help"
    findings = check_projection_drift(project_root, help_dir)
    return {"findings_count": len(findings), "findings": findings[:20]}


# ---------------------------------------------------------------------------
# Signal: SLOC / file / test counts
# ---------------------------------------------------------------------------


def _count_py_loc(root: Path) -> tuple[int, int]:
    files_count = 0
    lines_count = 0
    for path in root.rglob("*.py"):
        try:
            with path.open("r", encoding="utf-8", errors="replace") as f:
                lines_count += sum(1 for _ in f)
        except OSError:
            continue
        files_count += 1
    return files_count, lines_count


def _signal_sloc(project_root: Path) -> dict[str, Any]:
    src_files, src_lines = _count_py_loc(project_root / "src")
    test_files, test_lines = _count_py_loc(project_root / "tests")
    if src_files == 0:
        raise RuntimeError(f"no source files found under {project_root / 'src'}")
    ratio = round(test_lines / src_lines, 2) if src_lines else None
    return {
        "src_files": src_files,
        "src_lines": src_lines,
        "test_files": test_files,
        "test_lines": test_lines,
        "test_to_src_ratio": ratio,
    }


# ---------------------------------------------------------------------------
# Signal: TODO markers
# ---------------------------------------------------------------------------


def _signal_todos(project_root: Path) -> dict[str, Any]:
    src_dir = project_root / "src"
    count = 0
    for path in src_dir.rglob("*.py"):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        count += len(_TODO_RE.findall(text))
    return {"count": count}


# ---------------------------------------------------------------------------
# Signal: open PRs / issues (gh CLI)
# ---------------------------------------------------------------------------


def _gh_open_count(args: list[str], *, timeout: int) -> int:
    proc = subprocess.run(
        ["gh", *args],
        capture_output=True,
        text=True,
        timeout=timeout,
        check=True,
    )
    data = json.loads(proc.stdout)
    return len(data)


def _signal_open_prs_issues(*, timeout: int) -> dict[str, Any]:
    open_prs = _gh_open_count(
        ["pr", "list", "--state", "open", "--json", "number"], timeout=timeout
    )
    open_issues = _gh_open_count(
        ["issue", "list", "--state", "open", "--json", "number"], timeout=timeout
    )
    return {"open_prs": open_prs, "open_issues": open_issues}


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def collect_snapshot(
    project_root: Path,
    *,
    repo_slug: str = DEFAULT_REPO_SLUG,
    timeout: int = DEFAULT_TIMEOUT_SECONDS,
) -> dict[str, Any]:
    """Collect every signal, isolating failures per-signal.

    Never raises: any signal that fails is captured as
    ``{"status": "unavailable", "reason": ...}`` inside the returned
    snapshot rather than propagating.
    """
    project_root = Path(project_root)
    signals: dict[str, dict[str, Any]] = {
        "coverage": _safe(_signal_coverage, repo_slug, timeout=timeout),
        "complexity": _safe(_signal_complexity, project_root),
        "churn": _safe(_signal_churn, project_root, timeout=timeout),
        "doc_import_audit": _safe(_signal_doc_import_audit, project_root, timeout=timeout),
        "docs_wiring_audit": _safe(_signal_docs_wiring_audit, project_root, timeout=timeout),
        "help_completeness": _safe(_signal_help_completeness, project_root, timeout=timeout),
        "projection_drift": _safe(_signal_projection_drift, project_root),
        "sloc": _safe(_signal_sloc, project_root),
        "todos": _safe(_signal_todos, project_root),
        "open_prs_issues": _safe(_signal_open_prs_issues, timeout=timeout),
    }
    return {
        "schema_version": SCHEMA_VERSION,
        "collected_at": datetime.now(timezone.utc).isoformat(),
        "project_root": str(project_root),
        "repo_slug": repo_slug,
        "signals": signals,
    }


def latest_llm_report(project_root: Path) -> str | None:
    """Repo-relative path to the newest ``docs/reports/library-health-*.md``.

    Filenames are date-stamped (``library-health-YYYY-MM-DD.md``), so
    a lexicographic sort orders them chronologically. Returns
    ``None`` when no report has been written yet.
    """
    reports_dir = Path(project_root) / "docs" / "reports"
    if not reports_dir.is_dir():
        return None
    candidates = sorted(reports_dir.glob("library-health-*.md"))
    if not candidates:
        return None
    latest = candidates[-1]
    try:
        return str(latest.relative_to(project_root))
    except ValueError:
        return str(latest)


# ---------------------------------------------------------------------------
# Persistence — mirrors attune.ops.sweep_results' atomic-write pattern
# ---------------------------------------------------------------------------


def health_dir(attune_home: Path) -> Path:
    """Return ``<attune_home>/ops/health/`` (created if missing)."""
    out = Path(attune_home).joinpath(*RESULTS_SUBDIR)
    out.mkdir(parents=True, exist_ok=True)
    return out


def _atomic_write_json(target: Path, payload: dict[str, Any]) -> None:
    out_dir = target.parent
    fd, tmp_name = tempfile.mkstemp(prefix=f".{target.stem}.", suffix=".json.tmp", dir=str(out_dir))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)
        os.replace(tmp_name, target)
    except Exception:  # noqa: BLE001
        # INTENTIONAL: cleanup-and-reraise, not a mask — this catch
        # exists only so the temp file never leaks; the bare `raise`
        # preserves the original exception unchanged.
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def _snapshot_filename(collected_at: str) -> str:
    # ISO timestamps contain ':' which is awkward in filenames on
    # some filesystems; substitute for a safe, still-sortable form.
    return collected_at.replace(":", "-") + ".json"


def persist_snapshot(snapshot: dict[str, Any], attune_home: Path) -> Path:
    """Atomically write ``snapshot`` to a timestamped file + ``latest.json``.

    Returns the path of the timestamped file (not ``latest.json``).
    """
    out_dir = health_dir(attune_home)
    target = out_dir / _snapshot_filename(snapshot["collected_at"])
    _atomic_write_json(target, snapshot)
    _atomic_write_json(out_dir / "latest.json", snapshot)
    return target


def read_latest(attune_home: Path) -> dict[str, Any] | None:
    """Read the most recently persisted snapshot, or ``None`` if absent/corrupt."""
    target = health_dir(attune_home) / "latest.json"
    if not target.exists():
        return None
    try:
        with target.open("r", encoding="utf-8") as f:
            data: dict[str, Any] = json.load(f)
        return data
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("health_snapshot: latest.json at %s is unreadable: %s", target, exc)
        return None


def is_stale(
    snapshot: dict[str, Any] | None, *, max_age_hours: int = DEFAULT_STALE_AFTER_HOURS
) -> bool:
    """True when ``snapshot`` is missing, malformed, or older than ``max_age_hours``."""
    if snapshot is None:
        return True
    collected_at = snapshot.get("collected_at")
    if not collected_at:
        return True
    try:
        collected = datetime.fromisoformat(collected_at)
    except ValueError:
        return True
    if collected.tzinfo is None:
        collected = collected.replace(tzinfo=timezone.utc)
    return datetime.now(timezone.utc) - collected > timedelta(hours=max_age_hours)


def run_and_persist(
    project_root: Path,
    attune_home: Path,
    *,
    repo_slug: str = DEFAULT_REPO_SLUG,
    timeout: int = DEFAULT_TIMEOUT_SECONDS,
) -> Path:
    """Collect a fresh snapshot and persist it. Convenience for CLI + refresh route."""
    snapshot = collect_snapshot(project_root, repo_slug=repo_slug, timeout=timeout)
    return persist_snapshot(snapshot, attune_home)


# ---------------------------------------------------------------------------
# Background-thread refresh runner (used by the dashboard's Refresh route)
# ---------------------------------------------------------------------------


class HealthRefreshRunner:
    """Owns the single in-flight background snapshot refresh, if any.

    The collector calls blocking subprocesses and a blocking HTTP
    request, so it cannot run on the asyncio event loop without
    stalling every other request. A plain daemon thread (per decision
    2 — "background refresh", no scheduler) keeps the HTTP route
    handlers non-blocking: ``start()`` returns immediately, and
    ``running`` lets the page poll for completion.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._thread: threading.Thread | None = None

    @property
    def running(self) -> bool:
        with self._lock:
            return self._thread is not None and self._thread.is_alive()

    def start(
        self,
        project_root: Path,
        attune_home: Path,
        *,
        repo_slug: str = DEFAULT_REPO_SLUG,
        timeout: int = DEFAULT_TIMEOUT_SECONDS,
    ) -> bool:
        """Start a refresh in a background thread.

        Returns ``False`` (no-op) if a refresh is already running —
        single concurrent job by design, same discipline as
        ``HelpRegenRunner``.
        """
        with self._lock:
            if self._thread is not None and self._thread.is_alive():
                return False
            thread = threading.Thread(
                target=self._run,
                args=(project_root, attune_home),
                kwargs={"repo_slug": repo_slug, "timeout": timeout},
                daemon=True,
                name="health-snapshot-refresh",
            )
            self._thread = thread
            thread.start()
            return True

    @staticmethod
    def _run(project_root: Path, attune_home: Path, *, repo_slug: str, timeout: int) -> None:
        try:
            run_and_persist(project_root, attune_home, repo_slug=repo_slug, timeout=timeout)
        except Exception:  # noqa: BLE001
            # INTENTIONAL: this runs off the main thread with no
            # caller to propagate to — an uncaught exception here
            # would only surface in Python's default thread
            # excepthook (easy to miss). Log it instead; the next
            # page load / Refresh click can retry.
            logger.exception("health_snapshot: background refresh failed")


# ---------------------------------------------------------------------------
# CLI entry — ``python -m attune.ops.health_snapshot``
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    from attune.ops.config import attune_home as resolve_attune_home

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-root",
        default=".",
        help="Project root to collect signals from (default: cwd)",
    )
    parser.add_argument(
        "--attune-home",
        default=None,
        help="Override ATTUNE_HOME (defaults to $ATTUNE_HOME or ~/.attune)",
    )
    parser.add_argument(
        "--repo-slug", default=DEFAULT_REPO_SLUG, help="GitHub 'owner/repo' for coverage lookup"
    )
    parser.add_argument(
        "--timeout", type=int, default=DEFAULT_TIMEOUT_SECONDS, help="Per-signal timeout, seconds"
    )
    args = parser.parse_args(argv)

    project_root = Path(args.project_root).expanduser().resolve()
    attune_home = (
        Path(args.attune_home).expanduser().resolve() if args.attune_home else resolve_attune_home()
    )

    target = run_and_persist(
        project_root, attune_home, repo_slug=args.repo_slug, timeout=args.timeout
    )
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
