"""Tests for scripts/check_doc_audit_blocks.py (docs-link-prevalidation).

Regression guards for the audit-block reader:
- broken *links* ("target does not exist") detected;
- broken *imports* ("module not importable") NOT detected (out of scope);
- "Line N (code fence)" Location suffix tolerated;
- header/separator rows + non-error severities ignored;
- file-level override skips the file;
- no audit block / unreadable file degrade safely;
- warn mode always exits 0 (DECIDE-1).

Loads the script via importlib (matches the existing scripts-test pattern).
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

SCRIPT_PATH = Path(__file__).resolve().parents[3] / "scripts" / "check_doc_audit_blocks.py"


@pytest.fixture(scope="module")
def mod():
    spec = importlib.util.spec_from_file_location("_check_doc_audit_blocks", SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    m = importlib.util.module_from_spec(spec)
    sys.modules["_check_doc_audit_blocks"] = m
    spec.loader.exec_module(m)
    return m


# A realistic block mirroring docs/how-to/release-prep.md: a broken
# import (out of scope), two broken links (in scope), header + separator.
_REAL_BLOCK = """# Release Prep

Body text.

## Unresolved references

> Auto-generated by attune-author fact-check.

| Location | Severity | Issue |
|---|---|---|
| Line 7 (code fence) | error | `from release import …` — module not importable |
| Line 96 | error | `[concept](../concepts/tool-release-prep.md)` — target does not exist |
| Line 97 | warning | `[maybe](../x.md)` — target does not exist |
| Line 98 | error | `[quickstart](../quickstarts/skill-x.md)` — not found among documentation files |
"""


def test_detects_broken_links_only(mod):
    links = mod.find_broken_links(_REAL_BLOCK)
    lines = {bl.line for bl in links}
    # 96 (target does not exist) + 98 (not found among ...) — both error.
    assert lines == {96, 98}
    # 7 is a broken import (excluded); 97 is a warning (excluded).
    assert 7 not in lines
    assert 97 not in lines


def test_code_fence_suffix_tolerated(mod):
    # The Location cell "Line 7 (code fence)" must parse without breaking
    # the row — even though that row is later excluded as an import.
    block = (
        "## Unresolved references\n"
        "| Line 12 (code fence) | error | `[x](../missing.md)` — target does not exist |\n"
    )
    assert {bl.line for bl in mod.find_broken_links(block)} == {12}


def test_no_audit_block_returns_empty(mod):
    assert mod.find_broken_links("# Doc\n\nNo audit here.\n") == []


def test_block_ends_at_next_h2(mod):
    # Rows under a later h2 must not be read as audit rows.
    text = (
        "## Unresolved references\n"
        "| Line 5 | error | `[a](../gone.md)` — target does not exist |\n"
        "## Something else\n"
        "| Line 99 | error | `[b](../also-gone.md)` — target does not exist |\n"
    )
    assert {bl.line for bl in mod.find_broken_links(text)} == {5}


def test_override_skips_file(mod):
    assert mod.override_reason("<!-- attune-skip-link-check: WIP draft -->") == "WIP draft"


def test_empty_override_reason_is_not_a_skip(mod):
    assert mod.override_reason("<!-- attune-skip-link-check:   -->") is None
    assert mod.override_reason("no comment here") is None


def test_header_and_separator_rows_ignored(mod):
    block = "## Unresolved references\n" "| Location | Severity | Issue |\n" "|---|---|---|\n"
    assert mod.find_broken_links(block) == []


# --- main() / CLI ---------------------------------------------------------


def test_main_warn_mode_exits_zero_with_findings(mod, tmp_path, capsys):
    f = tmp_path / "doc.md"
    f.write_text(_REAL_BLOCK, encoding="utf-8")
    rc = mod.main([str(f)])
    assert rc == 0  # warn mode (DECIDE-1)
    out = capsys.readouterr().out
    assert "Line 96" in out and "Line 98" in out


def test_main_skips_overridden_file(mod, tmp_path, capsys):
    f = tmp_path / "doc.md"
    f.write_text(
        "<!-- attune-skip-link-check: legacy doc -->\n" + _REAL_BLOCK,
        encoding="utf-8",
    )
    assert mod.main([str(f)]) == 0
    assert "skipped per override: legacy doc" in capsys.readouterr().out


def test_main_unreadable_file_does_not_crash(mod, tmp_path):
    missing = tmp_path / "nope.md"
    assert mod.main([str(missing)]) == 0  # never fail the commit on I/O


def test_main_clean_file_is_quiet(mod, tmp_path, capsys):
    f = tmp_path / "clean.md"
    f.write_text("# Clean\n\nNo audit block.\n", encoding="utf-8")
    assert mod.main([str(f)]) == 0
    assert capsys.readouterr().out == ""
