#!/usr/bin/env python3
"""Project the probe registry from run-records (FREE — no LLM).

Phase 3 of docs/specs/workflow-behavioral-validation/ (D3, hardened by
D6/D7/D9): the registry table is DERIVED from per-run JSON records,
never hand-edited. Mechanics ruled by the spec:

- **Commit order is the ordering key** (D9 round-3 finding 1): the
  projector selects, per workflow, the record whose file was added
  LATEST in Git history. ``ran_at`` is informational provenance only —
  a future-skewed wall clock must never win. Untracked (not yet
  committed) records rank newest: they are about to be committed.
- **Rebuild from scratch, idempotent** (D7): the whole table is
  regenerated from the full append-only record set on every run; the
  projector never diffs against the existing table, so re-projection
  cannot regress anything.
- **Dispositions ledger** (D3): the one hand-authored file,
  ``dispositions.md`` — workflows intentionally without a probe, and
  why. Workflows with neither a record nor a disposition render as
  "not yet probed", never as clean.

Usage::

    python scripts/project_probe_registry.py            # write registry.md
    python scripts/project_probe_registry.py --check    # drift guard:
        exit 1 if the committed registry.md does not match a fresh
        projection (CI-safe, free)

Records live in ``docs/specs/workflow-behavioral-validation/records/``,
one JSON per probe run, schema (design.md § Registry):
``workflow, fixture, receipt_type, verdict (pass|fail|crash), cost_usd,
duration_s, ran_at, runner_version, git_sha, evidence``.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SPEC_DIR = REPO_ROOT / "docs" / "specs" / "workflow-behavioral-validation"
RECORDS_DIR = SPEC_DIR / "records"
REGISTRY_PATH = SPEC_DIR / "registry.md"
DISPOSITIONS_PATH = SPEC_DIR / "dispositions.md"

_HEADER = """# Probe registry — PROJECTED, do not hand-edit

Generated by `scripts/project_probe_registry.py` from `records/`.
The verdict/cost/last-run columns are the latest real run per workflow
(latest by GIT COMMIT ORDER of the record file — `ran_at` is provenance
only, never the ordering key). Re-run the projector after committing
new records; `--check` is the CI drift guard.

| Workflow | Verdict | Cost (USD) | Duration (s) | Ran at (UTC) | Tree | Record |
|----------|---------|------------|--------------|--------------|------|--------|
"""


def load_records(records_dir: Path) -> list[dict[str, Any]]:
    """Load every record JSON, attaching its filename."""
    records: list[dict[str, Any]] = []
    if not records_dir.is_dir():
        return records
    for path in sorted(records_dir.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            print(f"warning: skipping unreadable record {path.name}: {exc}", file=sys.stderr)
            continue
        if not isinstance(data, dict) or "workflow" not in data:
            print(f"warning: skipping malformed record {path.name}", file=sys.stderr)
            continue
        data["_file"] = path.name
        records.append(data)
    return records


def commit_order(records_dir: Path) -> dict[str, int]:
    """Map record filename -> the commit-order index that ADDED it.

    Earlier commits get lower indexes. Files never committed (untracked
    or staged-only) are absent from the map; callers rank them NEWEST.
    Returns an empty map when the directory is not in a Git repo
    (scratch mode — ordering then falls back to (ran_at, filename),
    which is acceptable only for local scratch, never for the tracked
    registry; the tracked records dir is always in-repo).
    """
    try:
        out = subprocess.run(
            [
                "git",
                "log",
                "--reverse",
                "--diff-filter=A",
                "--format=%x00%H",
                "--name-only",
                "--",
                str(records_dir),
            ],
            cwd=str(records_dir.parent),
            capture_output=True,
            text=True,
            timeout=30,
            check=True,
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return {}
    order: dict[str, int] = {}
    index = 0
    for line in out.splitlines():
        if line.startswith("\x00"):
            index += 1
            continue
        name = Path(line.strip()).name
        if line.strip() and name not in order:
            order[name] = index
    return order


def _rank(record: dict[str, Any], order: dict[str, int]) -> tuple:
    """Sort key: commit order first (untracked = newest), then ran_at
    and filename purely as deterministic tie-breaks within one commit."""
    fname = record["_file"]
    committed = order.get(fname)
    return (
        committed if committed is not None else float("inf"),
        str(record.get("ran_at", "")),
        fname,
    )


def latest_per_workflow(
    records: list[dict[str, Any]], order: dict[str, int]
) -> dict[str, dict[str, Any]]:
    """Pick, per workflow, the record ranked latest."""
    latest: dict[str, dict[str, Any]] = {}
    for record in records:
        name = str(record["workflow"])
        if name not in latest or _rank(record, order) > _rank(latest[name], order):
            latest[name] = record
    return latest


def parse_dispositions(path: Path) -> dict[str, str]:
    """Read the hand-authored dispositions ledger.

    Format: markdown bullets ``- **workflow-name** — reason``. Returns
    workflow -> reason.
    """
    dispositions: dict[str, str] = {}
    if not path.exists():
        return dispositions
    current: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("- **") and "**" in stripped[4:]:
            name, _, rest = stripped[4:].partition("**")
            current = name.strip()
            dispositions[current] = rest.lstrip(" —-–:").strip()
        elif (
            current and stripped and not stripped.startswith("- ") and not stripped.startswith("#")
        ):
            # Wrapped continuation line of the current bullet.
            dispositions[current] = f"{dispositions[current]} {stripped}".strip()
        else:
            current = None
    for name, reason in dispositions.items():
        if not reason:
            dispositions[name] = "(no reason recorded)"
    return dispositions


def render(
    latest: dict[str, dict[str, Any]],
    fleet: list[str],
    dispositions: dict[str, str],
) -> str:
    """Render the full registry markdown, deterministically."""
    lines = [_HEADER.rstrip("\n")]
    for name in sorted(latest):
        record = latest[name]
        verdict = str(record.get("verdict", "?")).upper()
        cost = record.get("cost_usd", 0.0)
        duration = record.get("duration_s", 0.0)
        ran_at = record.get("ran_at", "?")
        sha = str(record.get("git_sha", ""))[:9] or "?"
        lines.append(
            f"| {name} | {verdict} | {cost:.4f} | {duration:.1f} "
            f"| {ran_at} | {sha} | `records/{record['_file']}` |"
        )

    unprobed = [n for n in sorted(set(fleet)) if n not in latest]
    lines.append("")
    lines.append("## Not yet probed")
    lines.append("")
    if not unprobed:
        lines.append("(every fleet workflow has at least one record)")
    else:
        lines.append(
            "Workflows with NO run-record. Per the spec, absence is "
            "'not yet probed', never 'clean'. Reasons are hand-authored "
            "in `dispositions.md`."
        )
        lines.append("")
        for name in unprobed:
            reason = dispositions.get(
                name, "NO DISPOSITION RECORDED — needs a probe or a dispositions entry"
            )
            lines.append(f"- **{name}** — {reason}")
    lines.append("")
    return "\n".join(lines)


def default_fleet() -> list[str]:
    """The registered workflow names (the fleet the registry covers)."""
    from attune.workflows import list_workflows

    return [w["name"] for w in list_workflows()]


def project(fleet: list[str] | None = None) -> str:
    records = load_records(RECORDS_DIR)
    order = commit_order(RECORDS_DIR)
    latest = latest_per_workflow(records, order)
    dispositions = parse_dispositions(DISPOSITIONS_PATH)
    return render(latest, fleet if fleet is not None else default_fleet(), dispositions)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed registry.md differs from a fresh projection",
    )
    args = parser.parse_args(argv)

    content = project()
    if args.check:
        existing = REGISTRY_PATH.read_text(encoding="utf-8") if REGISTRY_PATH.exists() else ""
        if existing != content:
            print(
                "registry.md is STALE — re-run scripts/project_probe_registry.py "
                "and commit the result",
                file=sys.stderr,
            )
            return 1
        print("registry.md matches a fresh projection")
        return 0

    REGISTRY_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {REGISTRY_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
