#!/usr/bin/env python3
"""Project the released attune-forms semantic token contract into the website.

The website consumes tracked JSON and generated CSS at Node runtime. This sync
tool is the explicit cross-repository release boundary; ``--check`` is the CI
drift guard and never writes.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import importlib.resources
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
JSON_DEST = ROOT / "website/design/semantic_tokens.json"
CSS_DEST = ROOT / "website/app/semantic-tokens.css"
MINIMUM_VERSION = (0, 9, 0)

COLOR_NAMES = (
    "action",
    "action_hover",
    "success",
    "warning",
    "danger",
    "recommendation",
    "neutral_text",
    "neutral_muted",
    "surface",
    "surface_raised",
    "border",
    "focus",
)
CSS_COLOR_NAMES = {
    "action_hover": "action-hover",
    "neutral_text": "text",
    "neutral_muted": "muted",
    "surface_raised": "surface-raised",
}


def _version_tuple(value: str) -> tuple[int, int, int]:
    match = re.match(r"^(?:\d+!)?(\d+)(?:\.(\d+))?(?:\.(\d+))?", value)
    if match is None:
        raise ValueError(f"invalid package version: {value!r}")
    return tuple(int(part or 0) for part in match.groups())  # type: ignore[return-value]


def _load_source(path: Path | None) -> tuple[dict[str, Any], str]:
    if path is not None:
        return json.loads(path.read_text(encoding="utf-8")), "source checkout"
    version = importlib.metadata.version("attune-forms")
    if _version_tuple(version) < MINIMUM_VERSION:
        raise RuntimeError(f"attune-forms>=0.9.0 required; installed {version}")
    resource = importlib.resources.files("attune_forms").joinpath("semantic_tokens.json")
    return json.loads(resource.read_text(encoding="utf-8")), version


def _color_lines(tokens: dict[str, Any], mode: str, indent: str) -> list[str]:
    colors = tokens["color"][mode]
    return [
        f"{indent}--semantic-{CSS_COLOR_NAMES.get(name, name.replace('_', '-'))}: "
        f"{colors[name]};"
        for name in COLOR_NAMES
    ]


def render_css(tokens: dict[str, Any], source_version: str) -> str:
    lines = [
        f"/* Generated by scripts/sync_form_design_tokens.py from attune-forms {source_version}. */",
        ":root {",
        *_color_lines(tokens, "light", "  "),
        f"  --semantic-radius-control: {tokens['radius']['control']};",
        f"  --semantic-radius-panel: {tokens['radius']['panel']};",
        f"  --semantic-space-xs: {tokens['spacing']['xs']};",
        f"  --semantic-space-sm: {tokens['spacing']['sm']};",
        f"  --semantic-space-md: {tokens['spacing']['md']};",
        f"  --semantic-space-lg: {tokens['spacing']['lg']};",
        f"  --semantic-motion-fast: {tokens['motion']['fast']};",
        f"  --semantic-motion-normal: {tokens['motion']['normal']};",
        f"  --semantic-target-min: {tokens['control']['minimum_target']};",
        "}",
        "",
        ":root.dark {",
        *_color_lines(tokens, "dark", "  "),
        "}",
        "",
        "@media (prefers-color-scheme: dark) {",
        "  :root:not(.light) {",
        *_color_lines(tokens, "dark", "    "),
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def _projection_is_stale(path: Path, expected: str) -> bool:
    """Treat a missing generated asset as drift, not an internal error."""
    return not path.is_file() or path.read_text(encoding="utf-8") != expected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, help="semantic_tokens.json from a checkout")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    tokens, source_version = _load_source(args.source)
    json_text = json.dumps(tokens, indent=2, ensure_ascii=False) + "\n"
    css_text = render_css(tokens, source_version if args.source is None else "0.9.0")
    expected = ((JSON_DEST, json_text), (CSS_DEST, css_text))
    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, text in expected
            if _projection_is_stale(path, text)
        ]
        if stale:
            raise SystemExit("semantic token projection drift: " + ", ".join(stale))
        print(f"semantic token projection clean (attune-forms {source_version})")
        return 0
    for path, text in expected:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print(f"projected semantic tokens from attune-forms {source_version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
